steps:
  - name: Download Drupal 7
    plugin: Shell
    command: "drush dl drupal-7.x --destination=/var/www/html"
  - name: Make Module Dirs
    plugin: Shell
    command: "mkdir /var/www/html/sites/all/modules/contrib && mkdir /var/www/html/sites/all/modules/contrib/contextual_view_modes"
  - name: Move contextual_view_modes source to contrib dir
    command: "mv /src/* /var/www/html/sites/all/modules/contrib/contextual_view_modes/"
  - name: Run install
    plugin: Shell
    command: "drush site-install --root=/var/www/html standard --db-url='mysqli://root:strongpassword@localhost/standard'"
  - name: Set file directory permissions
    plugin: Shell
    command: 'chown -R www-data:www-data /var/www/html/sites/default/files'
  - name: Enable and download dependencies
    plugin: Shell
    command: "drush --root=/var/www/html en contextual_view_modes -y"
  - name: Revert all features
    plugin: Shell
    command: 'drush --root="/var/www/html" fra -y'
  - name: Clear cache
    plugin: Shell
    command: 'drush --root="/var/www/html" cc all -y'
